### ISSUE TITLE
set the current page in view

### ISSUE THREAD

**Issue by ozone2k** [seeden/react-g-analytics#11]
I was reviewing the Google page on [Single Page Application Tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#tracking_virtual_pageviews). They recommend using the `ga('set', 'page', '/path')` command before sending the page view `ga('send', 'pageview')`.

I notice your historyListener method pushes the pageview directly. Would this prevent other events being tracked from registering the current view the event was invoked from? If so, would it be possible to include the set page before sending it?

(I'm new to react-router and ga, sorry if the question is too basic).

**Comment by seeden** [comment]
yes, you are right. I will add it. If I understand it correctly I need to add `ga('set', 'page', '/path')` before each call `ga('send', 'pageview')`

**Comment by seeden** [comment]
fixed in the new version
