### ISSUE TITLE
Expected a string value for field: "location". But found: "object"

### ISSUE THREAD

**Issue by baronnoraz** [seeden/react-g-analytics#12]
Perhaps, I missed it, but is there anything special that needs to be done when testing locally for react-router v4 integration?

    Running command: ga("set", {page: "/", title: "My App", location: http://localhost:3000/})
    Expected a string value for field: "location". But found: "object".
    log                      @ analytics_debug.js:10
    J                        @ analytics_debug.js:9
    La                       @ analytics_debug.js:16
    zc                       @ analytics_debug.js:30
    wc.set                   @ analytics_debug.js:29
    Y.b.(anonymous function) @ analytics_debug.js:38
    ad.set                   @ analytics_debug.js:56
    Y.b.(anonymous function) @ analytics_debug.js:38
    jf.R                     @ analytics_debug.js:68
    jf.H                     @ analytics_debug.js:65
    Z.P                      @ analytics_debug.js:72
    cd                       @ analytics_debug.js:58
    A                        @ analytics_debug.js:58
    (anonymous function)     @ analytics_debug.js:75
    (anonymous function)     @ analytics_debug.js:75

    Running command: ga("send", {hitType: "pageview"})
    Missing required field '"location"' for hit of type '"pageview"'
    ....same call stack as above....

The code isn't doing anything fancy, which is why it makes me wonder if the problem is the fact that my location is localhost. 

    import {BrowserRouter} from "react-g-analytics";

    const googleAnalyticsId = 'UA-XXXX';

    const App = () => (
        <BrowserRouter id={googleAnalyticsId}>
            <div className="container">
                <Header/>
                <Match exactly pattern="/" component={Home} />
                <Miss component={NoMatch}/>
                <Footer/>
            </div>
        </BrowserRouter>
    );
    export default App;

It looks to me like it would be happy if it had double quotes: `location: "http://localhost:3000/"`

Any help is greatly appreciated.  Thanks so much for the work on this component.

**Comment by seeden** [comment]
the component is using document.location I can disable whole component when canUseDOM is false. Is it acceptable solution for you?

**Comment by baronnoraz** [comment]
Since the error is coming from Google's analytics_debug.js, and document.location seems to be exactly the right thing to be passing, let me debug this some more and see if I can figure out the root of the problem.  Then we can figure out if a canUseDOM property would be helpful.

Thanks for the quick response!

**Comment by baronnoraz** [comment]
Ok, so I was using the Chrome extension Google Analytics Debugger 2.6, which is what was pulling in the analytics_debug.js.  If I turn off the extension, I don't get an error. So I think that's fine and no need for an update.

That being said the "location" should be the full URL, https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#location

So the full production analytics.js code must be handling a Location object being passed in whereas the analytics_debug.js does not.  I would be interested to see if changing the code to

    GoogleAnalytics.set({
          page: path,
          title: document.title,
          location: document.location.href
    });

continued to work for your Component or if it breaks anything.  It seems like that change would make the debugger extension happy.

At any rate, I don't think you should change anything.  When I have more time, I'll try to see if `document.location.href` works.  Thanks again for your help.
