### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by PascalPixel** [seeden/react-g-analytics#13]
```jsx
      <Match
        pattern='/en'
        render={() => (
          <Redirect to='/' />
        )}
      />
```
This works with react-router 4 but not your version :(

**Comment by seeden** [comment]
what you see in the analytics?

**Comment by PascalPixel** [comment]
I'm sure they're fine, but this doesn't redirect to / with react-g-analytics, but works fine using the regular react-router <BrowserRouter>

**Comment by seeden** [comment]
which version of react-router 4 are you using ?

**Comment by PascalPixel** [comment]
`4.0.0-alpha.6` sir

**Comment by seeden** [comment]
latest working version is 4.0.0-alpha.5

**Comment by PascalPixel** [comment]
T_T Can you update readme to say that? <3
