### ISSUE TITLE
Getting "Router is not presented in the component context." error

### ISSUE THREAD

**Issue by gautam-bst** [seeden/react-g-analytics#2]
I've just added GoogleAnalytics id="UA-24874896-10" tag in my app.js before RouteHandler tag as mentioned here "https://www.npmjs.com/package/react-g-analytics".

After adding, I am getting this in my console:

Warning: Failed Context Types: Required context `router` was not specified in `GoogleAnalytics`. Check the render method of `App`.

and

Uncaught Error: Router is not presented in the component context.

Can you please tell me what am I missing..?

**Comment by seeden** [comment]
Are you using react-router?

**Comment by gautam-bst** [comment]
Yes, I've included react-router (version 0.13.3) in app.js.

**Comment by seeden** [comment]
Can you provide your source code or more information? I am using it in the production with router 0.13.3 and it is working all right.

**Comment by seeden** [comment]
Are you using your AppComponent in the render component as parameter?

``` js
<Route name="index" handler={App} path="/">
```

I updated readme file. Please take look on the example.

**Comment by gautam-bst** [comment]
Yes I've included in route tag like 

"Route name="App" path="/" handler={App}"
......some routes nested within......
"DefaultRoute handler={SignIn}/"
"/Route"

**Comment by gautam-bst** [comment]
Hi
Did you got any time to see the code. It'll great if you help me resolve the problem.

Thanks

**Comment by seeden** [comment]
Can you send me your project or part of it to my email. I will try to fix it because I have no idea what is wrong with it

**Comment by gautam-bst** [comment]
Hi
I've mailed you a part of my project. Please check your inbox.

Thanks

**Comment by seeden** [comment]
If you are using latest version of react 0.14.0 and react-router 1.0.0-rc3 you can use latest version. It is working.
