### ISSUE TITLE
Problem with React Router 1.0.0rc1

### ISSUE THREAD

**Issue by mkotar** [seeden/react-g-analytics#3]
Hi,
There is a problem with react-g-analytics with newest version of React Router.

npm ERR! peerinvalid The package react-router@1.0.0-rc1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-g-analytics@0.1.0 wants react-router@0.13.x

**Comment by seeden** [comment]
Try latest version and let me know. It should be fine

**Comment by monte-hayward** [comment]
As of Oct 2nd: 
`npm ERR! peer invalid Peer ga-react-router@1.3.0 wants react-router@0.11.x - 0.13.x`
It seems that greater than or equal will not accept a major version difference.
`"react-router": ">=0.13.x"`

Also, npm has trouble doing a numeric comparison on their release version:  "v1.0.0-rc3". npm will ignore the ^v, but has no way to parse "-rc3".

**Comment by mkotar** [comment]
can you add a fix for this like:
  "peerDependencies": {
    "react": ">=0.13.x",
    "react-router": ">=0.13.x || ~1.0.0-rc3"
  },

?

**Comment by seeden** [comment]
It is used in the latest version. But I am not sure if it is a good fix.

**Comment by seeden** [comment]
If you are using latest version of react 0.14.0 and react-router 1.0.0-rc3 you can use latest version. It is working.
