### ISSUE TITLE
option to not load the google analytics script within the component

### ISSUE THREAD

**Issue by jonathanong** [seeden/react-g-analytics#6]
so i have a global `ga` variable immediately. what do you think?

**Comment by seeden** [comment]
Are you loading ga in different way?

**Comment by jonathanong** [comment]
yes, as a script tag.

**Comment by jonathanong** [comment]
o i c. https://github.com/seeden/react-g-analytics/blob/c639ef0de545e683efac94df650cc1fe97d9a6d0/src/index.js#L4 it skips that logic if `window.ga` is already defined. would love to have that in the docs!

**Comment by seeden** [comment]
I will add it. Thanks

**Comment by jonathanong** [comment]
Except I get this error: 

```
Warning: Failed propType: Required prop `id` was not specified in `GoogleAnalytics`. Check the render method of `App`.
```

maybe not make it required?

**Comment by seeden** [comment]
It makes sense

**Comment by seeden** [comment]
Readme updated.
ID is optional in new release
