### ISSUE TITLE
react router 2 support

### ISSUE THREAD

**Issue by bdefore** [seeden/react-g-analytics#7]
Perhaps use `context.router.setRouteLeaveHook` instead of `context.history.listen` ?

https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#lifecycle-mixin

**Comment by seeden** [comment]
I will take a look on it

**Comment by bdefore** [comment]
Ended up being more straightforward, as there's a `listen` on router now instead of history. #8

**Comment by rexxars** [comment]
@bdefore Do you have any example of how you're using this with React Router v2?

**Comment by bdefore** [comment]
@rexxars forgot to close this issue. this PR was merged https://github.com/seeden/react-g-analytics/pull/8

**Comment by seeden** [comment]
@rexxars you can use it in the same way like for the react-router 1.x

**Comment by slybridges** [comment]
Hi,
I stumbled upon this issue. The latest published version on NPM doesn't include react-router 2̀̀ support.
Could you publish a version including PR #8? :smile:
In the meantime I'll use the git version.
Thanks!
Sly

**Comment by seeden** [comment]
please use version 2.1

**Comment by slybridges** [comment]
Hi @seeden,

Thanks, however I seem to get the following errors with version 0.2.1:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `App`.warning
```

It was working fine with the version from PR #8. 
Has there been any change on how to use the library?

Thanks!

**Comment by seeden** [comment]
Are u using babel? I have changed babel 5 to babel 6.
If you are using commonjs you need to use

``` js
var GoogleAnalytics = require('react-g-analytics').default
```

if you are using ES6 syntax you can do

``` js
import GoogleAnalytics from 'react-g-analytics';
```

**Comment by seeden** [comment]
I added old behaviour to version 0.2.2
You can use old code

```
var GoogleAnalytics = require('react-g-analytics');
```

**Comment by slybridges** [comment]
:+1: indeed that solved it ! Thanks for the lightning fast fixing :)
